### ISSUE TITLE
Map - Filtering Doesn't seem to work

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#3]
When a user uses the "Legend" to filter the map to only display events, jurisdictions, or installations they can still bring up the information for any of the layers when they hover over it - even though it is not displayed.

Screenshot example of map where only Jurisdictions is selected - hovering over an area suddenly brings up an event.

![image](https://cloud.githubusercontent.com/assets/18744855/19316563/f189ed86-906f-11e6-8d29-c1a0cbec5e7f.png)

**Comment by sam-ffctn** [comment]
Hovering over hidden elements will no longer trigger the tooltip
http://ffctn.com/clients/on/sfm/M13/#country/ng!date=2014-01-01&focus=map
(I just pushed this change so you may need to clear your cache for it to update)

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn I cleared my cache and restarted my comp - but I'm still getting the tooltip popping up.

**Comment by sam-ffctn** [comment]
You where right, the bug was only on the events. Should now be fixed:
http://ffctn.com/clients/on/sfm/M14/#country/ng!date=2014-01-01&focus=map

Sorry about that.
